version: "3.3"
services:
    mysql:
        image: mysql
        container_name: my
        ports:
          - 3306:3306
        volumes:
            - data:/tmp
        secrets:
          - sec
        environment:
          MYSQL_PASSWORD_FILE: /run/secrets/sec
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_ROOT_PASSWORD_FILE: /run/secrets/sec
    server:
        image: node
        container_name: node
        ports:
          - 4000:4000
        secrets:
          - sec
        environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${USER}
          HOST: ${HOST}
          MYSQL_PASSWORD_FILE: /run/secrets/sec

volumes:
    data: 
      driver: local

secrets:
  sec:
    file: mm.sql